export const locales = ['tr', 'en', 'ar', 'fa'] as const;
export type Locale = typeof locales[number];
export const rtl = ['ar', 'fa'];
export function localePath(locale: Locale, path = '') { return locale === 'tr' ? (path || '/') : `/${locale}${path}`; }
export const galleryLabels: Record<Locale, string> = { tr: 'Galeri', en: 'Gallery', ar: 'المعرض', fa: 'گالری' };

const about = {
  tr: 'AMIR 77 İNŞAAT, CEO ve Genel Müdür Mohammad Rostam Sangari’nin Yalova’daki 10 yılı aşkın saha deneyimiyle, çok disiplinli inşaat uygulamalarını başlangıçtan nihai teslime kadar koordine eder.',
  en: 'Led by CEO and Managing Director Mohammad Rostam Sangari, AMIR 77 İNŞAAT coordinates multi-discipline construction execution in Yalova from initial works through final handover, drawing on more than 10 years of field experience.',
  fa: 'AMIR 77 İNŞAAT به مدیریت محمد رستم سنگری، مدیرعامل و مدیر اجرایی شرکت، با تکیه بر بیش از ۱۰ سال تجربهٔ میدانی در یالوا، اجرای چندرشته‌ای پروژه را از آغاز تا تحویل نهایی هماهنگ می‌کند.',
  ar: 'تنسّق AMIR 77 İNŞAAT، بقيادة محمد رستم سنگری الرئيس التنفيذي والمدير العام، تنفيذ الأعمال الإنشائية متعددة التخصصات في يالوفا من المراحل الأولى حتى التسليم النهائي، بالاستناد إلى خبرة ميدانية تتجاوز 10 سنوات.',
};
export const copy: Record<Locale, Record<string, string>> = {
  tr: { home:'Ana Sayfa', about:'Hakkımızda', services:'Hizmetler', projects:'Projeler', contact:'İletişim', quote:'Teklif Al', hero:'GÜVENLE\nİNŞA EDİYORUZ.', intro:'Yalova merkezli çok disiplinli inşaat uygulamaları ve anahtar teslim proje uygulaması.', viewProjects:'Projelerimizi İncele', expertise:'UZMANLIK\nALANLARIMIZ', selected:'PROJELER\nVE REFERANSLAR', aboutTitle:'SAHADA DENEYİM.\nUÇTAN UCA TESLİM.', aboutText:about.tr, final:'YENİ BİR\nPROJEYE Mİ\nBAŞLIYORSUNUZ?', finalText:'Projenizi birlikte değerlendirelim.', talk:'PROJENİZİ\nKONUŞALIM.', send:'Gönder' },
  en: { home:'Home', about:'About', services:'Services', projects:'Projects', contact:'Contact', quote:'Request a Quote', hero:'BUILDING\nWITH CONFIDENCE.', intro:'Multi-discipline construction execution and turnkey project delivery based in Yalova.', viewProjects:'View Projects', expertise:'AREAS OF\nEXPERTISE', selected:'PROJECTS\nAND REFERENCES', aboutTitle:'FIELD EXPERIENCE.\nEND-TO-END DELIVERY.', aboutText:about.en, final:'STARTING A\nNEW PROJECT?', finalText:'Let’s evaluate your project together.', talk:'LET’S TALK\nABOUT YOUR PROJECT.', send:'Send' },
  ar: { home:'الرئيسية', about:'من نحن', services:'الخدمات', projects:'المشاريع', contact:'اتصل بنا', quote:'اطلب عرضاً', hero:'نبني\nبثقة.', intro:'تنفيذ أعمال إنشائية متعددة التخصصات وتسليم مشاريع بنظام تسليم المفتاح من يالوفا.', viewProjects:'استعرض المشاريع', expertise:'مجالات\nخبرتنا', selected:'المشاريع\nوالمراجع', aboutTitle:'خبرة ميدانية.\nتسليم متكامل.', aboutText:about.ar, final:'هل تبدأ\nمشروعاً جديداً؟', finalText:'لنقيّم مشروعك معاً.', talk:'لنتحدث عن\nمشروعك.', send:'إرسال' },
  fa: { home:'خانه', about:'درباره ما', services:'خدمات', projects:'پروژه‌ها', contact:'تماس', quote:'درخواست پیشنهاد', hero:'با اطمینان\nمی‌سازیم.', intro:'اجرای چندرشته‌ای ساختمان و تحویل پروژه به‌صورت صفر تا صد در یالوا.', viewProjects:'مشاهده پروژه‌ها', expertise:'حوزه‌های\nتخصص ما', selected:'پروژه‌ها\nو مراجع', aboutTitle:'تجربه در میدان.\nتحویل یکپارچه.', aboutText:about.fa, final:'پروژه جدیدی\nآغاز می‌کنید؟', finalText:'پروژه‌تان را با هم بررسی کنیم.', talk:'درباره پروژه‌تان\nگفتگو کنیم.', send:'ارسال' },
};

const names: Record<Locale, readonly string[]> = {
  tr:['Beton Dökme','Kalıp İşleri','Demir Donatı İşleri','Duvar Örme','Çatı İşleri','Elektrik Tesisatı','Mekanik / Yapı Tesisatı','Fayans Uygulamaları','Seramik Uygulamaları','İç Mekân Tasarımı ve Dekorasyon Uygulamaları','İnce İşler / Tamamlama İşleri','Anahtar Teslim Proje Uygulaması'],
  en:['Concrete Pouring','Formwork','Reinforcement Works','Masonry / Wall Construction','Roof Works','Electrical Installations','Mechanical / Building Installations','Tile Installation','Ceramic Installation','Interior Design and Decoration Execution','Finishing Works','Turnkey Construction / End-to-End Project Delivery'],
  fa:['بتن‌ریزی','قالب‌بندی','آرماتوربندی','دیوارچینی','اجرای سقف','تأسیسات برق','تأسیسات مکانیکی و ساختمانی','اجرای کاشی','اجرای سرامیک','اجرای طراحی داخلی و دکوراسیون','کارهای تکمیلی و نازک‌کاری','اجرای صفر تا صد / کلید تحویل'],
  ar:['صب الخرسانة','أعمال القوالب','أعمال حديد التسليح','بناء الجدران','أعمال الأسقف','التمديدات الكهربائية','التمديدات الميكانيكية وتمديدات المباني','تركيب البلاط','تركيب السيراميك','تنفيذ التصميم الداخلي والديكور','أعمال التشطيبات','تنفيذ مشاريع تسليم المفتاح من البداية إلى النهاية'],
};
const serviceNameOverrides: Partial<Record<Locale, Record<number, string>>> = {
  tr: { 9: 'İç Mekân Tasarımı ve Dekorasyon Uygulamaları' },
  en: { 9: 'Interior Design and Decoration Execution' },
  fa: { 9: 'طراحی داخلی و اجرای دکوراسیون' },
  ar: { 9: 'التصميم الداخلي وتنفيذ الديكور' },
};
const slugs = ['concrete-pouring','formwork','reinforcement','masonry','roof-works','electrical-installations','mechanical-building-installations','tile-installation','ceramic-installation','interior-design-decoration','finishing-works','turnkey-construction'];
const images = ['/images/services/concrete-pouring-new.jpg','/images/services/formwork-new.jpg','/images/services/reinforcement-new.jpg','/images/services/masonry-new.jpg','/images/service-roof.png','/images/services/electrical-installations.png','/images/services/mechanical-building-installations.png','/images/services/tile-installation.png','/images/services/ceramic-installation.png','/images/services/interior-design-decoration.png','/images/services/finishing-works.png','/images/services/turnkey-construction.png'];
export const services = slugs.map((slug, index) => ({ slug, tr:names.tr[index], en:names.en[index], image:images[index] }));
export function serviceLabel(locale: Locale, index: number, fallback: string) { return serviceNameOverrides[locale]?.[index] || names[locale][index] || fallback; }
export const projects = [
  { slug: 'tuglar-insaat', name: 'Tuğlar İnşaat', image: '/images/projects/tuglar-insaat.jpg' },
  { slug: 'sefa-group-insaat', name: 'Sefa Group İnşaat', image: '/images/projects/sefa-group-insaat.jpg' },
  { slug: 'seyit-insaat', name: 'Seyit İnşaat', image: '/images/projects/seyit-insaat.jpg' },
  { slug: 'necip-oglu-insaat', name: 'Necip Oğlu İnşaat', image: '/images/projects/necip-oglu-insaat.jpg' },
  { slug: 'yalova-my-home', name: 'Yalova My Home', image: '/images/projects/yalova-my-home.jpg' },
  { slug: 'ay-yapi', name: 'AY YAPI', image: '/images/projects/ay-yapi.jpg' }
];
export const contact = { address:'Sahil, Atatürk Cd. No:3/A\n77600 LookCoffee / Çiftlikköy / Yalova', general:'', accounting:'0539 492 91 11', tax:'069 153 90 78' };
export const localeContent = {
  tr:{aboutHeading:'Yönetim ve uygulama yaklaşımımız',ceoLabel:'CEO / Genel Müdür',ceoName:'Mohammad Rostam Sangari',ceoBiography:'1993 doğumlu Mohammad Rostam Sangari, Yalova inşaat sektöründe 10 yılı aşkın profesyonel deneyime sahiptir. Büyük ölçekli inşaat projelerinde görev almış; sahadaki uygulama ve proje yönetimi deneyimiyle AMIR 77 İNŞAAT’ta planlama, ekip koordinasyonu, yapı, tesisat, tamamlama ve nihai teslim süreçlerini bütün olarak yönetmektedir.',turnkeyTitle:'Anahtar Teslim Proje Uygulaması',turnkeyText:'AMIR 77 İNŞAAT, proje uygulamasını başlangıç aşamasından nihai teslimine kadar; planlama, uygulama ekiplerinin koordinasyonu, yapı, tesisat, tamamlama ve son detayları kapsayacak biçimde üstlenebilir.',projectPending:'Proje görselleri ve doğrulanmış kapsam bilgileri bekleniyor.',viewProject:'Projeyi İncele',serviceIntro:'Çok disiplinli saha uygulamaları ile proje koordinasyonuna odaklanan çalışma yaklaşımı.',capabilities:'Hizmet kapsamı',scopePending:'Hizmet kapsamı proje gereksinimlerine göre netleştirilir.',executionProcess:'UYGULAMA SÜRECİ',relatedProjects:'İlgili projeler',relatedText:'Proje ilişkileri ve görselleri doğrulanmış saha verileriyle eklenecektir.',projectsIntro:'Referans isimleri aşağıda yer almaktadır. Görseller ve kapsam bilgileri yalnızca doğrulandığında yayımlanacaktır.',projectIntro:'Bu proje için doğrulanmış konum, kapsam, tarih ve görseller müşteriden bekleniyor.',projectOverview:'Proje özeti',projectOverviewText:'Bu sayfa gerçek proje bilgilerini görünür kılmak için tasarlanmıştır. Doğrulanmamış teknik veya ticari bilgi yayımlanmaz.',projectDetails:'Proje bilgileri',locationLabel:'Konum',servicesLabel:'Hizmetler',status:'Durum',dataPending:'Veri bekleniyor',nextProject:'Tüm projeler',contactTitle:'İletişim',hours:'Pazartesi–Cuma 08:00–18:00\nCumartesi 09:00–15:00\nPazar Kapalı',formLabels:['Ad soyad','Telefon','E-posta','Proje türü','Konum','Mesaj'],formStatus:'Form gönderim bağlantısı henüz yapılandırılmadı.'},
  en:{aboutHeading:'Leadership and delivery approach',ceoLabel:'CEO / Managing Director',ceoName:'Mohammad Rostam Sangari',ceoBiography:'Born in 1993, Mohammad Rostam Sangari has more than 10 years of professional experience in Yalova’s construction industry. He has worked on large-scale construction projects and, through hands-on execution and project-management experience, leads AMIR 77 İNŞAAT’s integrated planning, team coordination, structural, installation, finishing and final-handover processes.',turnkeyTitle:'Turnkey Construction / End-to-End Project Delivery',turnkeyText:'AMIR 77 İNŞAAT can undertake project execution from initial stages through final handover, including planning, coordination of execution teams, structural work, installations, finishing and final details.',projectPending:'Project imagery and verified scope information are pending.',viewProject:'View project',serviceIntro:'A delivery approach focused on multi-discipline site execution and project coordination.',capabilities:'Service scope',scopePending:'The scope is defined according to project requirements.',executionProcess:'EXECUTION PROCESS',relatedProjects:'Related projects',relatedText:'Project relationships and imagery will be added with verified site data.',projectsIntro:'Reference names are listed below. Imagery and scope details are published only when verified.',projectIntro:'Verified location, scope, dates and imagery for this project are pending from the client.',projectOverview:'Project overview',projectOverviewText:'This page is designed to present real project information. No unverified technical or commercial information is published.',projectDetails:'Project details',locationLabel:'Location',servicesLabel:'Services',status:'Status',dataPending:'Data pending',nextProject:'All projects',contactTitle:'Contact us',hours:'Monday–Friday 08:00–18:00\nSaturday 09:00–15:00\nSunday closed',formLabels:['Full name','Phone','Email','Project type','Location','Message'],formStatus:'The form submission integration has not been configured.'},
  fa:{aboutHeading:'مدیریت و رویکرد اجرایی',ceoLabel:'مدیرعامل / مدیر اجرایی',ceoName:'محمد رستم سنگری',ceoBiography:'محمد رستم سنگری، متولد ۱۹۹۳، بیش از ۱۰ سال سابقهٔ فعالیت حرفه‌ای در صنعت ساخت‌وساز یالوا دارد. او در پروژه‌های ساختمانی بزرگ حضور داشته و امروز با تکیه بر تجربهٔ عملی در اجرا و مدیریت پروژه، فرایندهای یکپارچهٔ برنامه‌ریزی، هماهنگی تیم‌ها، سازه، تأسیسات، تکمیل و تحویل نهایی AMIR 77 İNŞAAT را هدایت می‌کند.',turnkeyTitle:'اجرای صفر تا صد / کلید تحویل',turnkeyText:'AMIR 77 İNŞAAT می‌تواند مسئولیت اجرای پروژه را از مراحل آغازین تا تحویل نهایی، شامل برنامه‌ریزی، هماهنگی تیم‌های اجرایی، سازه، تأسیسات، تکمیل و جزئیات نهایی بر عهده بگیرد.',projectPending:'تصاویر پروژه و جزئیات تأییدشدهٔ محدودهٔ کار در انتظار دریافت است.',viewProject:'مشاهده پروژه',serviceIntro:'رویکردی متمرکز بر اجرای چندرشته‌ای در کارگاه و هماهنگی پروژه.',capabilities:'دامنهٔ خدمات',scopePending:'دامنهٔ خدمات بر اساس نیازهای پروژه مشخص می‌شود.',executionProcess:'فرایند اجرا',relatedProjects:'پروژه‌های مرتبط',relatedText:'ارتباط پروژه‌ها و تصاویر با تأیید اطلاعات کارگاه اضافه می‌شوند.',projectsIntro:'نام مراجع در ادامه آمده است. تصاویر و جزئیات محدودهٔ کار تنها پس از تأیید منتشر می‌شوند.',projectIntro:'موقعیت، محدودهٔ اجرا، زمان‌بندی و تصاویر تأییدشدهٔ این پروژه در انتظار دریافت از کارفرماست.',projectOverview:'معرفی پروژه',projectOverviewText:'این صفحه برای نمایش اطلاعات واقعی پروژه طراحی شده است؛ اطلاعات فنی یا تجاری تأییدنشده منتشر نمی‌شود.',projectDetails:'جزئیات پروژه',locationLabel:'موقعیت',servicesLabel:'خدمات',status:'وضعیت',dataPending:'در انتظار اطلاعات',nextProject:'همه پروژه‌ها',contactTitle:'تماس با ما',hours:'دوشنبه تا جمعه ۰۸:۰۰–۱۸:۰۰\nشنبه ۰۹:۰۰–۱۵:۰۰\nیکشنبه تعطیل',formLabels:['نام و نام خانوادگی','تلفن','ایمیل','نوع پروژه','موقعیت','پیام'],formStatus:'اتصال ارسال فرم هنوز پیکربندی نشده است.'},
  ar:{aboutHeading:'القيادة ومنهج التسليم',ceoLabel:'الرئيس التنفيذي / المدير العام',ceoName:'محمد رستم سنگری',ceoBiography:'محمد رستم سنگری، من مواليد 1993، يتمتع بخبرة مهنية تتجاوز 10 سنوات في قطاع البناء في يالوفا. شارك في مشاريع إنشائية كبيرة، ويقود اليوم، اعتماداً على خبرته العملية في التنفيذ وإدارة المشاريع، عمليات التخطيط المتكامل وتنسيق الفرق والأعمال الإنشائية والتمديدات والتشطيبات والتسليم النهائي في AMIR 77 İNŞAAT.',turnkeyTitle:'تنفيذ مشاريع تسليم المفتاح من البداية إلى النهاية',turnkeyText:'يمكن لـ AMIR 77 İNŞAAT تحمّل مسؤولية تنفيذ المشروع من مراحله الأولى حتى التسليم النهائي، بما يشمل التخطيط وتنسيق فرق التنفيذ والأعمال الإنشائية والتمديدات والتشطيبات والتفاصيل النهائية.',projectPending:'صور المشروع ومعلومات نطاق العمل المؤكدة قيد الانتظار.',viewProject:'استعرض المشروع',serviceIntro:'منهج تنفيذ يركز على الأعمال متعددة التخصصات في الموقع وتنسيق المشروع.',capabilities:'نطاق الخدمة',scopePending:'يتحدد نطاق الخدمة وفق متطلبات المشروع.',executionProcess:'مراحل التنفيذ',relatedProjects:'مشاريع ذات صلة',relatedText:'ستُضاف علاقات المشاريع وصورها عند توفر بيانات موقع مؤكدة.',projectsIntro:'تظهر أسماء المراجع أدناه. ولا تُنشر الصور وتفاصيل النطاق إلا بعد التحقق منها.',projectIntro:'الموقع ونطاق التنفيذ والتواريخ والصور المؤكدة لهذا المشروع بانتظار تزويد العميل بها.',projectOverview:'نبذة عن المشروع',projectOverviewText:'صُممت هذه الصفحة لعرض معلومات المشروع الحقيقية، ولا تُنشر معلومات فنية أو تجارية غير مؤكدة.',projectDetails:'تفاصيل المشروع',locationLabel:'الموقع',servicesLabel:'الخدمات',status:'الحالة',dataPending:'بانتظار البيانات',nextProject:'كل المشاريع',contactTitle:'تواصل معنا',hours:'الاثنين–الجمعة 08:00–18:00\nالسبت 09:00–15:00\nالأحد مغلق',formLabels:['الاسم الكامل','الهاتف','البريد الإلكتروني','نوع المشروع','الموقع','الرسالة'],formStatus:'لم يتم إعداد ربط إرسال النموذج بعد.'},
} as const;
export function localizedText(locale: Locale, key: string, fallback: string) { const value = (localeContent as Record<string, Record<string, unknown>>)[locale]?.[key]; return typeof value === 'string' ? value : fallback; }

export const ceoProfiles: Record<Locale, { biography: string[]; expertiseTitle: string; expertise: string[]; projectsTitle: string; projects: string[]; closing: string }> = {
  tr: {
    biography: ['1993 doğumlu Mohammad Rostam Sangari, Yalova inşaat sektöründe 10 yılı aşkın profesyonel deneyime sahiptir. Farklı ölçeklerdeki yapı projelerinin yönetim ve uygulamasında önemli bir deneyim edinmiştir.', 'Büyük ölçekli inşaat projelerinde görev alan Sangari, bugün AMIR 77 İNŞAAT Genel Müdürü olarak saha deneyimi ve uzman uygulama ekibiyle bir projenin başlangıcından nihai teslime kadar yönetilmesini sağlar.', 'Yaklaşımı yalnızca işin belirli bir bölümünü yürütmek değildir. AMIR 77; planlama, uygulama ekiplerinin koordinasyonu, yapı, tesisat, bina tamamlamaları ve nihai detaylar dâhil olmak üzere projeyi baştan sona, anahtar teslim olarak üstlenebilir.'],
    expertiseTitle: 'Uygulama alanları',
    expertise: ['Beton dökme ve betonarme yapılar', 'Kalıp işleri', 'Donatı ve demir işleri', 'Duvar örme', 'Çatı ve çatı kaplama işleri', 'Elektrik tesisatı', 'Yapı tesisatları', 'Fayans ve karo uygulamaları', 'Seramik uygulamaları', 'İç mekân tasarımı ve dekorasyon uygulaması', 'Bina tamamlama işleri', 'Baştan sona proje yönetimi ve uygulaması'],
    projectsTitle: 'Projeler ve uygulama iş birlikleri',
    projects: ['AY YAPI', 'Tuğlar İnşaat', 'Sefa Group İnşaat', 'Seyit İnşaat', 'Necip Oğlu İnşaat', 'Yalova My Home'],
    closing: 'Her projede hedef; başlangıçtan son ayrıntıya kadar kalite, taahhüt, ekip koordinasyonu ve doğru teslimata odaklanan düzenli ve kontrol edilebilir bir uygulama süreci oluşturmaktır. Mohammad Rostam Sangari ve AMIR 77 İNŞAAT, projeyi ilk tasarımdan teslime hazır bir yapıya dönüştüren uygulama ekibidir.'
  },
  en: {
    biography: ['Born in 1993, Mohammad Rostam Sangari has more than 10 years of professional experience in Yalova’s construction industry, with significant experience managing and delivering construction projects at different scales.', 'Having contributed to major construction projects, he now leads AMIR 77 İNŞAAT as Chief Executive Officer / Managing Director. Together with an experienced delivery team, he can manage a project from its first stage through final handover.', 'His approach goes beyond delivering an isolated scope of work. AMIR 77 can take responsibility for end-to-end, turnkey delivery: planning, coordinating execution teams, structural work, installations, building completion and final details.'],
    expertiseTitle: 'Delivery expertise',
    expertise: ['Concrete pouring and reinforced-concrete structures', 'Formwork', 'Reinforcement and steel work', 'Masonry / wall construction', 'Roof and roofing works', 'Electrical installations', 'Building installations', 'Tile and faience installation', 'Ceramic installation', 'Interior design and decoration execution', 'Building finishing works', 'End-to-end project management and delivery'],
    projectsTitle: 'Projects and delivery collaborations',
    projects: ['AY YAPI', 'Tuğlar İnşaat', 'Sefa Group İnşaat', 'Seyit İnşaat', 'Necip Oğlu İnşaat', 'Yalova My Home'],
    closing: 'The goal on every project is to establish an organised and controllable delivery process, from the first work through final details, with a focus on quality, commitment, team coordination and correct handover. Mohammad Rostam Sangari and AMIR 77 İNŞAAT are a delivery team that turns a project from its first design into a building ready for handover.'
  },
  fa: {
    biography: ['محمد رستم سنگری، متولد سال ۱۹۹۳، با بیش از ۱۰ سال سابقه فعالیت حرفه‌ای در صنعت ساخت‌وساز در یالووا، تجربه قابل‌توجهی در مدیریت و اجرای پروژه‌های ساختمانی در مقیاس‌های مختلف دارد.', 'او طی سال‌های فعالیت خود در اجرای پروژه‌های بزرگ ساختمانی حضور داشته و امروز به‌عنوان مدیرعامل AMIR 77 İNŞAAT، با تکیه بر تجربه میدانی و تیم اجرایی متخصص، توانایی مدیریت یک پروژه از مرحله آغاز تا تحویل نهایی را دارد.', 'رویکرد محمد رستم سنگری تنها اجرای بخشی از عملیات ساختمانی نیست؛ AMIR 77 می‌تواند مسئولیت اجرای یک پروژه را به‌صورت صفر تا صد و کلید تحویل (Anahtar Teslim) بر عهده بگیرد؛ از برنامه‌ریزی و هماهنگی تیم‌های اجرایی تا اجرای سازه، تأسیسات، تکمیل ساختمان و جزئیات نهایی.'],
    expertiseTitle: 'حوزه‌های اجرایی',
    expertise: ['بتن‌ریزی و اجرای سازه‌های بتنی', 'قالب‌بندی', 'آرماتوربندی و اجرای آهن', 'دیوارچینی', 'اجرای سقف و بام', 'تأسیسات برق', 'تأسیسات ساختمانی', 'اجرای کاشی و فایانس', 'اجرای سرامیک', 'طراحی و اجرای دکوراسیون داخلی', 'اجرای مراحل تکمیلی ساختمان', 'مدیریت و اجرای کامل پروژه به‌صورت صفر تا صد'],
    projectsTitle: 'پروژه‌ها و همکاری‌های اجرایی',
    projects: ['AY YAPI', 'Tuğlar İnşaat', 'Sefa Group İnşaat', 'Seyit İnşaat', 'Necip Oğlu İnşaat', 'Yalova My Home'],
    closing: 'هدف او در هر پروژه، ایجاد یک روند اجرایی منظم و قابل‌کنترل است؛ از شروع کار تا جزئیات نهایی، با تمرکز بر کیفیت اجرا، تعهد، هماهنگی تیم‌ها و تحویل صحیح پروژه. محمد رستم سنگری و AMIR 77 İNŞAAT؛ یک تیم اجرایی برای تبدیل پروژه از طرح اولیه به یک ساختمان آماده تحویل.'
  },
  ar: {
    biography: ['محمد رستم سنگری، من مواليد عام 1993، يتمتع بخبرة مهنية تزيد على 10 سنوات في قطاع البناء في يالوفا، وخبرة ملموسة في إدارة وتنفيذ المشاريع الإنشائية بمقاييس مختلفة.', 'شارك خلال مسيرته في تنفيذ مشاريع إنشائية كبيرة، ويعمل اليوم مديراً تنفيذياً لشركة AMIR 77 İNŞAAT، مستنداً إلى خبرته الميدانية وفريق التنفيذ المتخصص لقيادة المشروع من بدايته حتى التسليم النهائي.', 'ولا يقتصر نهجه على تنفيذ جزء من الأعمال الإنشائية؛ إذ يمكن لـ AMIR 77 تولي مسؤولية تنفيذ المشروع من البداية إلى النهاية بنظام تسليم المفتاح (Anahtar Teslim)، من التخطيط وتنسيق فرق التنفيذ إلى الأعمال الإنشائية والتمديدات وإكمال المبنى والتفاصيل النهائية.'],
    expertiseTitle: 'مجالات التنفيذ',
    expertise: ['صب الخرسانة وتنفيذ الهياكل الخرسانية', 'أعمال القوالب', 'التسليح وأعمال الحديد', 'بناء الجدران', 'تنفيذ الأسقف وأعمال السطح', 'التمديدات الكهربائية', 'تمديدات المباني', 'تركيب البلاط والقاشاني', 'تركيب السيراميك', 'التصميم الداخلي وتنفيذ الديكور', 'مراحل التشطيب النهائية للمبنى', 'الإدارة والتنفيذ الكامل للمشروع من البداية إلى النهاية'],
    projectsTitle: 'المشاريع وشراكات التنفيذ',
    projects: ['AY YAPI', 'Tuğlar İnşaat', 'Sefa Group İnşaat', 'Seyit İnşaat', 'Necip Oğlu İnşaat', 'Yalova My Home'],
    closing: 'الهدف في كل مشروع هو إنشاء عملية تنفيذ منظمة وقابلة للضبط، من بداية العمل إلى التفاصيل النهائية، مع التركيز على جودة التنفيذ والالتزام وتنسيق الفرق والتسليم الصحيح. محمد رستم سنگری وAMIR 77 İNŞAAT فريق تنفيذ يحوّل المشروع من المخطط الأولي إلى مبنى جاهز للتسليم.'
  }
};
