'use client';

import { FormEvent, useEffect, useState } from 'react';

type Item = { id: string; type: 'image' | 'video'; title: string; url: string; youtubeId: string | null; isPublished: boolean; position: number };

export default function AdminPanel({ authenticated }: { authenticated: boolean }) {
  const [loggedIn, setLoggedIn] = useState(authenticated), [items, setItems] = useState<Item[]>([]), [message, setMessage] = useState(''), [loading, setLoading] = useState(false);
  const load = async () => { const response = await fetch('/api/admin/media'); if (response.ok) setItems(await response.json()); };
  useEffect(() => { if (loggedIn) void load(); }, [loggedIn]);
  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); const password = new FormData(event.currentTarget).get('password'); const response = await fetch('/api/admin/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ password }) }); setLoading(false); if (!response.ok) return setMessage((await response.json()).error); setLoggedIn(true); setMessage(''); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); const response = await fetch('/api/admin/media', { method: 'POST', body: new FormData(event.currentTarget) }); const data = await response.json(); setLoading(false); if (!response.ok) return setMessage(data.error); event.currentTarget.reset(); setMessage('رسانه با موفقیت ثبت شد.'); await load(); }
  async function remove(item: Item) { if (!confirm(`«${item.title}» حذف شود؟`)) return; const response = await fetch('/api/admin/media', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify(item) }); if (!response.ok) return setMessage((await response.json()).error); await load(); }
  async function update(event: FormEvent<HTMLFormElement>, item: Item) { event.preventDefault(); const form = new FormData(event.currentTarget); setLoading(true); const response = await fetch('/api/admin/media', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: item.id, title: form.get('title'), position: form.get('position'), isPublished: form.get('isPublished') === 'on' }) }); const data = await response.json(); setLoading(false); if (!response.ok) return setMessage(data.error); setMessage('تغییرات ذخیره شد.'); await load(); }
  if (!loggedIn) return <main className="admin-shell"><form className="admin-login" onSubmit={login}><span>AMIR 77 / ADMIN</span><h1>ورود به پنل گالری</h1><label>رمز عبور<input name="password" type="password" required autoFocus /></label><button className="btn gold" disabled={loading}>{loading ? 'در حال ورود…' : 'ورود'}</button>{message && <p role="alert">{message}</p>}</form></main>;
  return <main className="admin-shell"><div className="admin-wrap"><header className="admin-header"><div><span>AMIR 77 / ADMIN</span><h1>مدیریت گالری</h1></div><button className="btn outline" onClick={async () => { await fetch('/api/admin/login', { method: 'DELETE' }); location.reload(); }}>خروج</button></header><form className="admin-form" onSubmit={submit}><h2>افزودن رسانه</h2><label>نوع رسانه<select name="type" defaultValue="image"><option value="image">عکس</option><option value="video">ویدیوی یوتیوب</option></select></label><label>عنوان<input name="title" required placeholder="مثلاً اجرای پروژه در یالوا" /></label><label>فایل عکس <small>برای ویدیو خالی بگذارید</small><input name="file" type="file" accept="image/*" /></label><label>لینک یوتیوب <small>برای عکس خالی بگذارید</small><input name="url" type="url" placeholder="https://www.youtube.com/watch?v=…" /></label><label>ترتیب نمایش<input name="position" type="number" defaultValue="0" min="0" /></label><button className="btn gold" disabled={loading}>{loading ? 'در حال ذخیره…' : 'ذخیره رسانه'}</button>{message && <p className="admin-message" role="status">{message}</p>}</form><section className="admin-list"><h2>رسانه‌های ثبت‌شده</h2>{items.length ? <div>{items.map(item => <article key={item.id}><div>{item.type === 'image' ? <img src={item.url} alt="" /> : <div className="video-preview">YouTube</div>}</div><form className="admin-item-form" onSubmit={event => void update(event, item)}><label>عنوان<input name="title" defaultValue={item.title} required /></label><label>ترتیب<input name="position" type="number" min="0" defaultValue={item.position} required /></label><label className="publish-toggle"><input name="isPublished" type="checkbox" defaultChecked={item.isPublished} /> منتشر شود</label><button type="submit" disabled={loading}>ذخیره</button></form><button className="delete-button" onClick={() => void remove(item)}>حذف</button></article>)}</div> : <p>هنوز رسانه‌ای ثبت نشده است.</p>}</section></div></main>;
}
