import Link from 'next/link';
import { Locale, copy, galleryLabels, projects, services, serviceLabel, localizedText, localePath } from './lib/data';
import { localProjectName, localText } from './lib/localize';
import { getSiteSettings } from './lib/site-settings';
export { Header, ContactForm } from './client-components';
export const lines=(s:string)=><>{s.split('\n').map((x,i)=><span key={i}>{x}{i<s.split('\n').length-1&&<br/>}</span>)}</>;
const socialProfiles=[{name:'Instagram',url:'https://www.instagram.com/amir77.insaat/',icon:<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/></svg>},{name:'YouTube',url:'https://www.youtube.com/@amir77insaat1',icon:<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12c0 3.4-.4 5.5-1.2 6.2C19 19 16.7 19 12 19s-7 0-7.8-.8C3.4 17.5 3 15.4 3 12s.4-5.5 1.2-6.2C5 5 7.3 5 12 5s7 0 7.8.8C20.6 6.5 21 8.6 21 12Z"/><path d="m10 9 5 3-5 3Z" className="social-play"/></svg>},{name:'TikTok',url:'https://www.tiktok.com/@amir77insaat',icon:<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 3v10.1a4.5 4.5 0 1 1-3.1-4.3v3a1.6 1.6 0 1 0 .1 2.7V3h3c.3 2.1 1.5 3.5 3.9 3.8v3c-1.5 0-2.8-.5-3.9-1.4"/></svg>}];
export function SocialLinks(){return <div className="social-links" aria-label="AMIR 77 İNŞAAT social media">{socialProfiles.map(profile=><a key={profile.name} href={profile.url} target="_blank" rel="noreferrer" aria-label={`AMIR 77 İNŞAAT on ${profile.name}`}>{profile.icon}<span className="sr-only">{profile.name}</span></a>)}</div>}
export async function Footer({ locale }: { locale: Locale }) {
  const t = copy[locale];
  const settings = await getSiteSettings();
  const defaultHours = locale === 'tr' ? 'Pazartesi–Cuma\n08:00–18:00\n\nCumartesi 09:00–15:00\nPazar Kapalı' : 'Monday–Friday 08:00–18:00\nSaturday 09:00–15:00\nSunday closed';
  const hours = localText(locale, 'hours', defaultHours);
  const address = localText(locale, 'footerAddress', 'Sahil, Atatürk Cd. No:3/A\n77600 LookCoffee / Çiftlikköy / Yalova / Türkiye');
  return <><footer className="footer"><div className="wrap footer-grid"><div className="footer-brand"><img className="footer-mark" src="/images/amir77insaat-logo.png" alt=""/><h3>AMIR 77<br/>İNŞAAT</h3>{settings.addressEnabled && <p>{address}</p>}</div><div><p><Link href={localePath(locale,'/services')}>{t.services}</Link><Link href={localePath(locale,'/projects')}>{t.projects}</Link><Link href={localePath(locale,'/gallery')}>{galleryLabels[locale]}</Link><Link href={localePath(locale,'/about')}>{t.about}</Link><Link href={localePath(locale,'/contact')}>{t.contact}</Link></p></div><div><p>{settings.general && <>{settings.general}<br/></>}{settings.accounting}<br/><br/>{hours}</p><SocialLinks/></div></div><div className="wrap footer-credit"><small>© {new Date().getFullYear()} AMIR 77 İNŞAAT</small><div className="footer-extras"><div google-add-preferred-source-btn=""/><small><a href="https://tavakolistudio.vercel.app/en" target="_blank" rel="noreferrer">Powered by <strong>TAVAKOLISTUDIO</strong></a></small></div></div></footer>{settings.whatsapp && <a className="whatsapp-float" href={`https://wa.me/${settings.whatsapp}`} target="_blank" rel="noreferrer" aria-label="WhatsApp"><svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16 3a13 13 0 0 0-11.1 19.8L3 29l6.4-1.7A13 13 0 1 0 16 3Zm0 23.7a10.6 10.6 0 0 1-5.4-1.5l-.4-.2-3.8 1 1-3.7-.3-.4A10.7 10.7 0 1 1 16 26.7Zm5.9-8c-.3-.2-1.9-.9-2.2-1s-.5-.2-.7.2-.8 1-.9 1.2-.3.3-.6.1a8.6 8.6 0 0 1-2.5-1.5 9.4 9.4 0 0 1-1.7-2.2c-.2-.3 0-.4.1-.6l.5-.5c.2-.2.2-.3.3-.5s0-.4 0-.5l-1-2.3c-.3-.7-.6-.6-.8-.6h-.7c-.2 0-.5.1-.8.4s-1 1.1-1 2.8 1 3.3 1.1 3.5a12.4 12.4 0 0 0 4.8 4.3c.7.3 1.2.5 1.6.6.7.2 1.3.2 1.8.1.5-.1 1.9-.8 2.1-1.5s.3-1.4.2-1.5-.3-.2-.6-.4Z"/></svg></a>}</>;
}
export function Final({locale}:{locale:Locale}){const t=copy[locale];return <section className="final"><div className="wrap"><h2 className="display">{lines(t.final)}</h2><p>{t.finalText}</p><Link className="btn gold" href={localePath(locale,'/contact')}>{t.quote}</Link></div></section>}
function ServiceFallbackIcon({slug}:{slug:string}){const common={viewBox:'0 0 48 48',fill:'none',stroke:'currentColor',strokeWidth:1.7,strokeLinecap:'round' as const,strokeLinejoin:'round' as const,'aria-hidden':true};if(slug==='electrical-installations')return <svg {...common}><path d="m27 4-13 20h10l-3 20 13-22H24z"/></svg>;if(slug==='mechanical-building-installations')return <svg {...common}><path d="M8 12h19a7 7 0 0 1 7 7v17M8 36h19a7 7 0 0 0 7-7V12"/><path d="M8 8v8m0 16v8m28-32v8m0 16v8"/></svg>;if(slug==='tile-installation')return <svg {...common}><path d="M7 7h15v15H7zm19 0h15v15H26zM7 26h15v15H7zm19 0h15v15H26z"/></svg>;if(slug==='ceramic-installation')return <svg {...common}><path d="m24 5 16 19-16 19L8 24z"/><path d="m15 24 9-11 9 11-9 11z"/></svg>;if(slug==='interior-design-decoration')return <svg {...common}><path d="M8 39V14l16-8 16 8v25M17 39V27h14v12M13 18h6m10 0h6"/></svg>;if(slug==='finishing-works')return <svg {...common}><path d="M10 38 31 17l6 6-21 21H10z"/><path d="m32 8 2 5 5 2-5 2-2 5-2-5-5-2 5-2z"/></svg>;return <svg {...common}><path d="M7 39 19 27l7 7L41 17"/><path d="M31 17h10v10"/><path d="M8 9h12v12H8z"/></svg>}
export function ServiceCards({locale,className=''}:{locale:Locale,className?:string}){return <div className={`service-grid ${className}`.trim()}>{services.map((service,index)=>{const label=serviceLabel(locale,index,locale==='tr'?service.tr:service.en);return <Link className="service-card" href={localePath(locale,`/services/${service.slug}`)} key={service.slug} target="_blank" rel="noreferrer"><div className={`service-image${service.image?' has-service-image':' service-image--placeholder'}`} style={service.image?{backgroundImage:`url('${service.image}')`}:undefined}><span className="service-image-mark" aria-hidden="true"><ServiceFallbackIcon slug={service.slug}/></span></div><div className="service-card-copy"><span className="service-num">{String(index+1).padStart(2,'0')}</span><h2 className="service-name">{label}</h2><span className="service-arrow" aria-hidden="true">↗</span></div></Link>})}</div>}
export function ProjectCards({locale,limit}:{locale:Locale,limit?:number}){return <div className="project-list">{projects.slice(0,limit).map((p,i)=>{const name=localProjectName(locale,i,p.name);return <article className="project-row" key={p.slug}><div className="project-image" style={{backgroundImage:`url('${p.image}')`,backgroundSize:'cover',backgroundPosition:'center'}}><span>{name}</span></div><div className="project-info"><div><span className="eyebrow">{String(i+1).padStart(2,'0')} / Yalova</span><h3>{name}</h3><p>{localizedText(locale,'projectPending','Project imagery and verified scope information are pending.')}</p></div><Link className="btn outline" href={localePath(locale,`/projects/${p.slug}`)}>{localizedText(locale,'viewProject','View project')} →</Link></div></article>})}</div>}
